Chatbot in get startedpg
Akshima-Ghai/OneEducationalWebsiteForAll pull request #183
Opened 2021-07-23 09:57 UTC by urmi-256

2021-07-23 11:26 UTC, deeqakkk requested changes
It's amazing, you did it really well.
just make few minor changes like:

Chatbox should open up when user clicks on "doubt assitance".
And i guess we can't interact by typing a msg, enable that as well so that user can type his query.

2021-07-25 14:36 UTC, urmi-256 commented
https://user-images.githubusercontent.com/71149323/126902969-cec8e433-324d-4e3f-96f9-9260e04b4bf2.mp4

Updated accordingly. Is this now ok? Shall I give a new pr or add in this one only?

2021-07-26 08:09 UTC, deeqakkk approved these changes

2021-07-26 08:09 UTC, merged

2021-07-26 08:09 UTC, deeqakkk commented
>  2021-07-25.20-01-32.mp4 
> Updated accordingly. Is this now ok? Shall I give a new pr or add in this one only? @deeqakkk

NO no , no need of a new PR, its perfect.